blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/kolirt/laravel-api-response?tab=readme-ov-file#laravel-api-response
    about: Check the documentation for guides and examples.